//Alarmas logicas

#define AL_TRIPEXT 0
#define AL_TRIPINT 1
#define AL_MAYOR 2
#define AL_MINOR 3
#define AL_FIELDCOM 4
#define AL_FIELDVARS 5
#define AL_MASTERCOM 6
#define AL_HIGHOVS 7
#define AL_LOWOVS 8
#define AL_STRTIMEOUT 9
#define AL_STPTIMEOUT 10
#define AL_UNLTIMEOUT 11
#define AL_MEF1 12
#define AL_MEF2 13
#define AL_MEF3 14
#define AL_MEF 15
#define AL_MEPW 16
#define AL_CONF 17
#define AL_UNSTB 18
#define AL_REVERSEPW 19
#define AL_NOAUX 20

#define NUM_ALARMS 21

#define ALARM_LEVELS {1,1,1,0,1,0,0,1,0,1,1,1,0,0,0,1,1,1,1,1,1}

#define ALARM_DESC {"DISPARO EXTERNO","DISPARO INTERNO","FALLO MAYOR","FALLO MENOR","PERDIDA COM CON CAMPO","ERROR DE VARIABLES DE CAMPO","PERDIDA COM CON MAESTROS","SOBREVELOCIDAD ALTA","SOBREVELOCIDAD BAJA","TIMEOUT EN ARRANQUE","TIMEOUT EN PARADA","TIMEOUT EN DESCARGA","ERROR DE MEDIDA EN VAR VEL 1","ERROR DE MEDIDA EN VAR VEL 2","ERROR DE MEDIDA EN VAR VEL 3","ERROR DE MEDIDA DE VELOCIDAD","ERROR DE MEDIDA DE POTENCIA","FALLO EN CONFIGURACION","REGULACION INESTABLE","INVERSION DE POTENCIA","ELEMENTOS AUX NO DISPONIBLES"}
